# - name: play1
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: PLAY-1 and TASK-1
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-1 and TASK-1"
#   - name: PLAY-1 and TASK-2
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-1 and TASK2"
# - name: PLAY2
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: PLAY-2 and TASK-1
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-2 and TASK-1"
#   - name: PLAY-2 and TASK-2
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-2 and TASK-2"    


- name: play 1
  hosts: web
  become: yes
  tasks:
  - name: play 1 , task1 
    ansible.builtin.debug:
      msg: "Play 1 and task-1"
  - name: play 2 , task 2
    ansible.builtin.debug:  
      msg: "Play 1 and Task TASK-2"
- name: play 2
  hosts: web 
  become: yes 
  tasks: 
  - name: play 2 , task1 
    ansible.builtin.debug:
      msg: " Play 2 and Task TASK-1"
  - name: Play 2 , Task 2 
    ansible.builtin.debug:
      msg: "Play 2 and Task-2"          


      




        




