- name: play1
  hosts: localhost
  become: yes
  tasks:
  - name: PLAY-1 and TASK-1
    ansible.builtin.debug:
      msg: "Hello i m from PLAY-1 and TASK-1"
  - name: PLAY-1 and TASK-2
    ansible.builtin.debug:
      msg: "Hello i m from PLAY-1 and TASK2"
- name: PLAY2
  hosts: localhost
  become: yes
  tasks:
  - name: PLAY-2 and TASK-1
    ansible.builtin.debug:
      msg: "Hello i m from PLAY-2 and TASK-1"
  - name: PLAY-2 and TASK-2
    ansible.builtin.debug:
      msg: "Hello i m from PLAY-2 and TASK-2"                
