# - name: play1
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: PLAY-1 and TASK-1
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-1 and TASK-1"
#   - name: PLAY-1 and TASK-2
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-1 and TASK2"
# - name: PLAY2
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: PLAY-2 and TASK-1
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-2 and TASK-1"
#   - name: PLAY-2 and TASK-2
#     ansible.builtin.debug:
#       msg: "Hello i m from PLAY-2 and TASK-2"    


# - name: play-1
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: play-1 and task-1
#     ansible.builtin.debug:
#       msg: "PLAY-1 and TASK-1"
#   - name: play-1 and task-1
#     ansible.builtin.debug:
#       msg: "PLAY-1 and TASK-2"
# - name: Play-2
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: play-2 and task-1 
#     ansible.builtin.debug:
#       msg: "PLAY-2 and TASK-1"
#   - name: play-2 and task-2
#     ansible.builtin.debug:
#       msg: "PLAY-2 and TASK-2"       

# - name: play-1
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: play-1 and task-1
#     ansible.builtin.debug:
#       msg: "PLAY-1 and TASK-1"
#   - name: play-1 and task-2
#     ansible.builtin.debug:
#       msg: "PLAY-1 and TASK-2"
# - name: play-2
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: play-2 and task-1 
#     ansible.builtin.debug:
#       msg: "PLAY-2 and TASK-1"
#   - name: play-2 and task-2
#     ansible.builtin.debug:
#       msg: "PLAY-2 and TASK-2"         

# - name: play level
#   hosts: web
#   become: yes
#   tasks: 
#   - name: play-1
#     ansible.builtin.debug:
#       msg: "Play1,task1"
#   - name: play-2 
#     ansible.builtin.debug:  
#       msg: "Play1,task2"

# - name: Play level 2
#   hosts: web
#   become: yes
#   tasks:
#   - name: play 2
#     ans

- name: Play1 
  hosts: localhost 
  become: yes
  tasks:
  - name: Play 1,task1 
    ansible.builtin.debug:
      msg: "Play 1 and Task TASK-1"
  - name: Play1 and task2 
    ansible.builtin.debug:
      msg: "Play 1 and Task TASK-2"

- name: Play2 
  hosts: localhost 
  become: yes
  tasks:
  - name: Play2 and task-1
    ansible.builtin.debug:
      msg: "Play 2 Task 1 "

  - name: Play 2 and Task-2 
    ansible.builtin.debug:
      msg: "Play 2 and Task2"    

      




        




