# - name: variables
#   hosts: localhost
#   vars:
#     course: "Ansible"
#     Trainer: "Sivakumar"
#     Duration: "120hr"
#   become: yes
#   tasks:
#   - name: print information
#     ansible.builtin.debug:
#       msg: "Hi we are learning course:::{{course}} from trainer::{{Trainer}} duration is {{Duration}}"

- name: variables
  hosts: localhost
  become: yes
  vars:
    Course: "DOCKER"
  tasks:
  - name: override
    vars:
      Course: "KUBS"
    ansible.builtin.debug:
      msg: "{{Override: Course}}"
  - name: inheritance
    ansible.builtin.debug:
      msg: "{{Inheritance:Course}}"       
