# - name: vars
#   hosts: localhost
#   vars:
#     Course: "Ansible"
#     Trainer: "Siva"
#     Duration: 120
#   become: yes
#   tasks:
#   - name: print overrider
#     vars:
#       Course: "Ansible1"
#       Trainer: "Siva1"
#       Duration: 1200 
#     ansible.builtin.debug:
#       msg: "Course::{{Course}} {{Trainer}} {{Duration}}"      

#   - name: print inheritance
#     ansible.builtin.debug:
#       msg: "Course::{{Course}} {{Trainer}} {{Duration}}"    

# - name: vars
#   hosts: localhost
#   become: yes
#   vars:
#     Course: "Docker"
#   tasks:
#   - name: Override
#     vars:
#       Course: "Kubs"
#     ansible.builtin.debug:
#       msg: "{{Course}}"
#   - name: Inheritance
#     ansible.builtin.debug:
#       msg: "{{Course}}"     

- name: vars
  hosts: web
  become: yes
  vars:
  - course: "Docker"
  tasks:
  - name: print
    vars:
    - course: "Kubs"
    ansible.builtin.debug:  
      msg:"{{course}}" 

