# - name: vars
#   hosts: localhost
#   vars:
#     Course: "Ansible"
#     Trainer: "Siva"
#     Duration: 120
#   become: yes
#   tasks:
#   - name: print overrider
#     vars:
#       Course: "Ansible1"
#       Trainer: "Siva1"
#       Duration: 1200 
#     ansible.builtin.debug:
#       msg: "Course::{{Course}} {{Trainer}} {{Duration}}"      

#   - name: print inheritance
#     ansible.builtin.debug:
#       msg: "Course::{{Course}} {{Trainer}} {{Duration}}"    

# - name: vars
#   hosts: localhost
#   become: yes
#   vars:
#     Course: "Docker"
#   tasks:
#   - name: Override
#     vars:
#       Course: "Kubs"
#     ansible.builtin.debug:
#       msg: "{{Course}}"
#   - name: Inheritance
#     ansible.builtin.debug:
#       msg: "{{Course}}"     

# - name: vars
#   hosts: web
#   become: yes
#   vars:
#   - course: "Docker"
#   tasks:
#   - name: print
#     vars:
#     - course: "Kubs"
#     ansible.builtin.debug:  
#       msg:"{{course}}" 

# - name: varplay
#   hosts: localhost 
#   become: yes
#   vars:
#     Course: "Ansible-1" 
#   tasks:
#   - name: variable play 
#     vars:
#       Course: "Ansible-2"
#     ansible.builtin.debug:
#       msg: "{{Course}}"
#   - name: playlevel
#     ansible.builtin.debug:
#       msg: "{{Course}}"   

# - name: variables 
#   hosts: localhost 
#   become: yes
#   vars:
#     Course: "Ansible-1" 
#   tasks:
#   - name: Task level 
#     vars:
#       Course: "Ansible-2"
#     ansible.builtin.debug:
#       msg: "{{Course}}"
#   - name:  Play level variables 
#     ansible.builtin.debug:
#       msg: "{{Course}}"   


- name: variables 
  hosts: localhost 
  become: yes
  vars:
    Course: "Docker"
  tasks:
  - name: task level 
    vars: 
      Course: "Ansible-2"
    ansible.builtin.debug:
      msg: "{{Course}}"
  - name: play level 
    ansible.builtin.debug: 
      msg: "{{Course}}"


