# - name: variables
#   hosts: localhost
#   vars_files:
#   - vars.yaml
#   tasks:
#   - name: print var files
#     ansible.builtin.debug:
#       msg: "Hi, we are learning {{Course}}"

- name: var files
  hosts: web
  become: yes
  vars_files:
    vars.yaml
  tasks:
  - name: var files 
    ansible.builtin.debug:
      msg: "{{Course}}"