- name: vars with preg
  hosts: localhost
  become: yes
  vars:
    WISHES: "WISHES from play level"
  vars_prompt:
    name: WISHES
    prompt: "Pls enter WISHES from prompt level"
    private: false
  vars_files:
    var.yaml
  tasks:
  - name: vars with pref
    ansible.builtin.debug:
      msg: "{{WISHES}}"
