- name: var pref
  host: localhost
  become: yes
  vars:
    WISEHS: "vars from play level"
  vars_prompt:
    name: WISEHS
    prompt: "Pls enter wishes from prompt"
    private: false
  tasks:
  - name: "Hello"  
  # vars_files:
  #   vars.yaml    
  # tasks:
  # - name: var preg
  #   vars:
  #     WISEHS: "vars from task level"
  #   ansible.builtin.debug:
  #     msg: "{{WISHES}}"  
