# - name: datatypes
#   hosts: localhost
#   become: yes
#   vars:
#   - Course: "AWS"
#     tools:
#     - Linux
#     - shell
#     - ansible
#     Exp:
#       Devops: 3
#       AWS: 2volts
#       Dokcer: 5
#     RealProject: true
#   tasks:
#   - name: datatypes
#     ansible.builtin.debug:
#       msg: "{{Course}} {{tools}} {{Exp}} {{RealProject}}"

- name: data type
  hosts: web
  become: no
  vars:
    COURSE: "DOcker"
    tools:
    - linux 
    - kubs 
    - robo
    exp:
      ansible: 2 
      linux: 5
      kubs: 8

  tasks: 
  - name: vars 
    ansible.builtin.debug:
      msg: "{{}}"