- name: datatypes
  hosts: localhost
  become: yes
  vars:
  - Course: "AWS"
    tools:
    - Linux
    - shell
    - ansible
    Exp:
      Devops: 3
      AWS: 2
      Dokcer: 5
    RealProject: true
  tasks:
  - name: datatypes
    ansible.builtin.debug:
      msg: "{{Course}} {{tools}} {{Exp}} {{RealProject}}"