- name: conditions
  hosts: web
  become: yes
  tasks:
  - name: conditions
    ansible.builtin.command: id expense
    ignore_errors: true
    register: USER

  - name: register
    ansible.builtin.debug:
      msg: "{{USER}}" 

  - name: say hello
    ansible.builtin.debug:
      msg: "Hello"        