# - name: conditions
#   hosts: localhost
#   become: yes
#   vars_prompt:
#   - name: number
#     prompt: "Enter number:::"
#     private: false
#   tasks:
#   - name: number > 
#     ansible.builtin.debug:
#       msg: "{{number}} greater  or equal  10"
#     when: number | int >= 10
#   - name: number < 
#     ansible.builtin.debug:
#       msg: "{{number}} less than"
#     when: number | int < 10   

- name: number
  hosts: localhost
  become: no
  vars_prompt:
  - name: number
    prompt: "Enter num"
    private: false
  tasks:
  - name: number
    ansible.builtin.debug:
      msg: "{{number}} greater than 10"
    when: number | int >= 10