# - name: default
#   hosts: localhost
#   become: no
#   tasks:
#   - name: default
#     ansible.builtin.debug:
#       msg: "{{Course | default('Ansible')}}"

# - name: default
#   hosts: localhost
#   become: no
#   tasks:
#   - name: default
#     ansible.builtin.debug:
#       msg: "{{Course | default('Ansible')}}"

# - name: default
#   hosts: localhost
#   become: no
#   vars:
#   - greetings: "Good morning"
#   tasks:
#   - name: lower
#     ansible.builtin.debug:
#       msg: "{{ greetings | lower }}"

# - name: lower
#   hosts: localhost
#   become: yes
#   vars:
#   - greeetings: "Hi from play level"
#   tasks:
#   - name: lower
#     ansible.builtin.debug:
#       msg: "{{ greeetings | lower}}"


# - name: default
#   hosts: localhost
#   become: no
#   vars:
#   - greetings: "Good morning"
#   tasks:
#   - name: lower
#     ansible.builtin.debug:
#       msg: "{{ greetings | upper }}"  

# - name: dups
#   hosts: localhost
#   become: no
#   vars:
#   - numbers: [1,1,2,3,3,4,4,5,5]
#   tasks:
#   - name: dups
#     ansible.builtin.debug:
#       msg: "{{numbers | unique}}"   

- name: dups
  hosts: localhost
  become: yes
  vars:
  - numbers: [1,1,2,2,3,3,4,4,5,5]
  tasks:
  - name: dups
    ansible.builtin.debug:
      msg: "{{numbers|unique}} min: {{numbers|min}}"

# - name: dups
#   hosts: localhost
#   become: no
#   vars:
#   - numbers: [1,1,2,3,3,4,4,5,5]
#   tasks:
#   - name: dups
#     ansible.builtin.debug:
#       msg: "min: {{numbers | min}}, max:: {{numbers | max}}"     

# - name: dict2items
#   hosts: localhost
#   become: no
#   vars:
#     my_dict: 
#      course: "docker"
#      trainer: "nnr"
#   tasks:
#   - name: dict2items
#     ansible.builtin.debug:
#       msg: "before dict {{my_dict}}"
#   - name: dict2items
#     ansible.builtin.debug:
#       msg: "After dict {{my_dict| dict2items }}"  

- name: dict2items
  hosts: localhost
  become: yes
  vars:
    my_dict:
      course: "docker"
      trainer: "nnr"
  tasks:
  - name: dict
    ansible.builtin.debug:
      msg: "{{my_dict| dict2items}}"

- name: items2dict
  hosts: localhost
  become: no
  vars:
    my_list: 
    - {'key': 'course', 'value': 'docker'}
    - {'key': 'trainer', 'value': 'nnr'}
  tasks:
  - name: dict2items
    ansible.builtin.debug:
      msg: "before dict {{my_list}}"
  - name: dict2items
    ansible.builtin.debug:
      msg: "After dict {{my_list| items2dict }}"  




       
      



