- name: items2dict
  hosts: localhost
  become: no
  vars:
    my_list: 
    - {'key': 'course', 'value': 'docker'}
    - {'key': 'trainer', 'value': 'nnr'}
  tasks:
  - name: dict2items
    ansible.builtin.debug:
      msg: "before dict {{my_list}}"
  - name: dict2items
    ansible.builtin.debug:
      msg: "After dict {{my_list| items2dict }}"  