- name: dict2items
  hosts: localhost
  become: no
  vars:
    my_dict: 
     course: "docker"
     trainer: "nnr"
  tasks:
  - name: dict2items
    ansible.builtin.debug:
      msg: "before dict {{my_dict}}"
  - name: dict2items
    ansible.builtin.debug:
      msg: "After dict {{my_dict| dict2items }}" 