# - name: Loops
#   hosts: localhost
#   become: no
#   tasks: 
#   - name: Loops
#     ansible.builtin.debug:
#       msg: "Hello {{item}}"
#     loop:
#     - ansible
#     - linux
#     - docker  

# - name: Loops
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: Loops
#     ansible.builtin.debug:
#       msg: "{{item}}"
#     loop:
#     - ansible
#     - docker
#     - kubs  

- name: Loop
  hosts: web
  become: yes
  tasks:
  - name: loops 
    ansible.builtin.debug:
      msg: "{{item}}"
    loop:
    - nginx 
    - docker 
    - ansible 
    - kubs  
