# - name: Loops
#   hosts: localhost
#   become: no
#   tasks: 
#   - name: Loops
#     ansible.builtin.debug:
#       msg: "Hello {{item}}"
#     loop:
#     - ansible
#     - linux
#     - docker  

# - name: Loops
#   hosts: localhost
#   become: yes
#   tasks:
#   - name: Loops
#     ansible.builtin.debug:
#       msg: "{{item}}"
#     loop:
#     - ansible
#     - docker
#     - kubs  

- name: loop
  hosts: web 
  become: yes
  tasks: 
  - name: print 
    ansible.builtin.command:
      msg: "{{item}}"
    loop:
    - ansible 
    - docker     
